Feature one
mesielepush/weather-app pull request #1
Opened 2020-07-03 23:32 UTC by mesielepush

Pull request to merge the final section of the weather app to the Development branch. All systems work, linters passes and UI is not ugly.

2020-07-05 11:28 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @mesielepush 

Really nice and original UI :smiley_cat: I really love it.
However, although everything is working correctly, one thing is out to the requirement.
![Screenshot at 2020-07-05 12:25:08](https://user-images.githubusercontent.com/8848104/86531612-b6e6e080-beba-11ea-932d-ed48b6c7f253.png)
That screenshot show that every time the user click on the toggle button to change the temperature unit, the application does a request to the API. Which is not good.
The conversion from Fahrenheit to Celsius and vice-versa must be done locally without any request.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-06 15:21 UTC, mesielepush commented
Doing separate requests for Celcius and Fahrenheit it's a microverse requirement.
![image](https://user-images.githubusercontent.com/48403308/86610064-6f239000-bf72-11ea-96f2-44589bdeedd7.png)

2020-07-07 02:28 UTC, bellom approved these changes
## Hi @mesielepush :clap: 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck with your next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun J. Bello**
**_Slack Handle - @sean bellom_**

2020-07-07 02:28 UTC, bellom commented on src/js/central.js
> +      alert('City does not exist');
### [Optional]
This should be production code, we shouldn't have `alert`, please remove the `alert`.

2020-07-07 03:34 UTC, merged